docker-vanguardia:
	sudo docker run -it --rm -P -p 50055:50055 lab3:latest  go run Vanguardia/vanguardia.go
docker-broker:
	sudo docker run -it --rm -P -p 50051:50051 lab3:latest  go run Broker/broker.go
docker-tierra:
	sudo docker run -it --rm -P -p 50052:50052 lab3:latest  go run Tierra/tierra.go
docker-titan:
	sudo docker run -it --rm -P -p 50053:50053 lab3:latest  go run Titan/titan.go
docker-marte:
	sudo docker run -it --rm -P -p 50054:50054 lab3:latest  go run Marte/marte.go
docker-guardianes:
	sudo docker run -it --rm -P -p 50056:50056 lab3:latest  go run Guardianes/guardianes.go