// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: Proto/message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Consistency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actualizar     string  `protobuf:"bytes,1,opt,name=actualizar,proto3" json:"actualizar,omitempty"`
	RelojVectorial []int32 `protobuf:"varint,2,rep,packed,name=relojVectorial,proto3" json:"relojVectorial,omitempty"`
}

func (x *Consistency) Reset() {
	*x = Consistency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Consistency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consistency) ProtoMessage() {}

func (x *Consistency) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consistency.ProtoReflect.Descriptor instead.
func (*Consistency) Descriptor() ([]byte, []int) {
	return file_Proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *Consistency) GetActualizar() string {
	if x != nil {
		return x.Actualizar
	}
	return ""
}

func (x *Consistency) GetRelojVectorial() []int32 {
	if x != nil {
		return x.RelojVectorial
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recibo int32 `protobuf:"varint,1,opt,name=recibo,proto3" json:"recibo,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_Proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetRecibo() int32 {
	if x != nil {
		return x.Recibo
	}
	return 0
}

type Signal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Aviso int32 `protobuf:"varint,1,opt,name=aviso,proto3" json:"aviso,omitempty"`
}

func (x *Signal) Reset() {
	*x = Signal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_Proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *Signal) GetAviso() int32 {
	if x != nil {
		return x.Aviso
	}
	return 0
}

type MergeAnswerString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logs           string  `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	RelojVectorial []int32 `protobuf:"varint,2,rep,packed,name=relojVectorial,proto3" json:"relojVectorial,omitempty"`
}

func (x *MergeAnswerString) Reset() {
	*x = MergeAnswerString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeAnswerString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeAnswerString) ProtoMessage() {}

func (x *MergeAnswerString) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeAnswerString.ProtoReflect.Descriptor instead.
func (*MergeAnswerString) Descriptor() ([]byte, []int) {
	return file_Proto_message_proto_rawDescGZIP(), []int{3}
}

func (x *MergeAnswerString) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

func (x *MergeAnswerString) GetRelojVectorial() []int32 {
	if x != nil {
		return x.RelojVectorial
	}
	return nil
}

type SolicitudPlaneta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Solicitud string `protobuf:"bytes,1,opt,name=solicitud,proto3" json:"solicitud,omitempty"`
}

func (x *SolicitudPlaneta) Reset() {
	*x = SolicitudPlaneta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudPlaneta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudPlaneta) ProtoMessage() {}

func (x *SolicitudPlaneta) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudPlaneta.ProtoReflect.Descriptor instead.
func (*SolicitudPlaneta) Descriptor() ([]byte, []int) {
	return file_Proto_message_proto_rawDescGZIP(), []int{4}
}

func (x *SolicitudPlaneta) GetSolicitud() string {
	if x != nil {
		return x.Solicitud
	}
	return ""
}

type PlanetaDesignado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DireccionAsignada string `protobuf:"bytes,1,opt,name=direccionAsignada,proto3" json:"direccionAsignada,omitempty"`
	PuertoAsignado    string `protobuf:"bytes,2,opt,name=puertoAsignado,proto3" json:"puertoAsignado,omitempty"`
}

func (x *PlanetaDesignado) Reset() {
	*x = PlanetaDesignado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlanetaDesignado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanetaDesignado) ProtoMessage() {}

func (x *PlanetaDesignado) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanetaDesignado.ProtoReflect.Descriptor instead.
func (*PlanetaDesignado) Descriptor() ([]byte, []int) {
	return file_Proto_message_proto_rawDescGZIP(), []int{5}
}

func (x *PlanetaDesignado) GetDireccionAsignada() string {
	if x != nil {
		return x.DireccionAsignada
	}
	return ""
}

func (x *PlanetaDesignado) GetPuertoAsignado() string {
	if x != nil {
		return x.PuertoAsignado
	}
	return ""
}

//Mensajes Vanguardia- Broker
type Crear struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Valor  string `protobuf:"bytes,3,opt,name=valor,proto3" json:"valor,omitempty"` //int32 check cambio
}

func (x *Crear) Reset() {
	*x = Crear{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Crear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Crear) ProtoMessage() {}

func (x *Crear) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Crear.ProtoReflect.Descriptor instead.
func (*Crear) Descriptor() ([]byte, []int) {
	return file_Proto_message_proto_rawDescGZIP(), []int{6}
}

func (x *Crear) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Crear) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Crear) GetValor() string {
	if x != nil {
		return x.Valor
	}
	return ""
}

type CambioNombre struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector         string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	NombreOriginal string `protobuf:"bytes,2,opt,name=nombreOriginal,proto3" json:"nombreOriginal,omitempty"`
	NombreNuevo    string `protobuf:"bytes,3,opt,name=nombreNuevo,proto3" json:"nombreNuevo,omitempty"`
}

func (x *CambioNombre) Reset() {
	*x = CambioNombre{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CambioNombre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CambioNombre) ProtoMessage() {}

func (x *CambioNombre) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CambioNombre.ProtoReflect.Descriptor instead.
func (*CambioNombre) Descriptor() ([]byte, []int) {
	return file_Proto_message_proto_rawDescGZIP(), []int{7}
}

func (x *CambioNombre) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *CambioNombre) GetNombreOriginal() string {
	if x != nil {
		return x.NombreOriginal
	}
	return ""
}

func (x *CambioNombre) GetNombreNuevo() string {
	if x != nil {
		return x.NombreNuevo
	}
	return ""
}

type Actualizar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector     string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base       string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	NuevoValor string `protobuf:"bytes,3,opt,name=nuevoValor,proto3" json:"nuevoValor,omitempty"` //int32 check cambio
}

func (x *Actualizar) Reset() {
	*x = Actualizar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Actualizar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actualizar) ProtoMessage() {}

func (x *Actualizar) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actualizar.ProtoReflect.Descriptor instead.
func (*Actualizar) Descriptor() ([]byte, []int) {
	return file_Proto_message_proto_rawDescGZIP(), []int{8}
}

func (x *Actualizar) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Actualizar) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Actualizar) GetNuevoValor() string {
	if x != nil {
		return x.NuevoValor
	}
	return ""
}

type Borrar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *Borrar) Reset() {
	*x = Borrar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Borrar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Borrar) ProtoMessage() {}

func (x *Borrar) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Borrar.ProtoReflect.Descriptor instead.
func (*Borrar) Descriptor() ([]byte, []int) {
	return file_Proto_message_proto_rawDescGZIP(), []int{9}
}

func (x *Borrar) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Borrar) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

type CodigoRespuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codigo         int32   `protobuf:"varint,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
	Planeta        string  `protobuf:"bytes,2,opt,name=planeta,proto3" json:"planeta,omitempty"`
	RelojVectorial []int32 `protobuf:"varint,3,rep,packed,name=relojVectorial,proto3" json:"relojVectorial,omitempty"`
}

func (x *CodigoRespuesta) Reset() {
	*x = CodigoRespuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodigoRespuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodigoRespuesta) ProtoMessage() {}

func (x *CodigoRespuesta) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodigoRespuesta.ProtoReflect.Descriptor instead.
func (*CodigoRespuesta) Descriptor() ([]byte, []int) {
	return file_Proto_message_proto_rawDescGZIP(), []int{10}
}

func (x *CodigoRespuesta) GetCodigo() int32 {
	if x != nil {
		return x.Codigo
	}
	return 0
}

func (x *CodigoRespuesta) GetPlaneta() string {
	if x != nil {
		return x.Planeta
	}
	return ""
}

func (x *CodigoRespuesta) GetRelojVectorial() []int32 {
	if x != nil {
		return x.RelojVectorial
	}
	return nil
}

//Mensajes Guardianes - Broker y Broker - Planeta
type SoldadosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *SoldadosRequest) Reset() {
	*x = SoldadosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoldadosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoldadosRequest) ProtoMessage() {}

func (x *SoldadosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoldadosRequest.ProtoReflect.Descriptor instead.
func (*SoldadosRequest) Descriptor() ([]byte, []int) {
	return file_Proto_message_proto_rawDescGZIP(), []int{11}
}

func (x *SoldadosRequest) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *SoldadosRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

type SoldadosAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CantidadSoldados int32   `protobuf:"varint,1,opt,name=cantidadSoldados,proto3" json:"cantidadSoldados,omitempty"`
	PlanetaEmisor    string  `protobuf:"bytes,2,opt,name=planetaEmisor,proto3" json:"planetaEmisor,omitempty"`
	RelojVectorial   []int32 `protobuf:"varint,3,rep,packed,name=relojVectorial,proto3" json:"relojVectorial,omitempty"`
}

func (x *SoldadosAnswer) Reset() {
	*x = SoldadosAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_message_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoldadosAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoldadosAnswer) ProtoMessage() {}

func (x *SoldadosAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_message_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoldadosAnswer.ProtoReflect.Descriptor instead.
func (*SoldadosAnswer) Descriptor() ([]byte, []int) {
	return file_Proto_message_proto_rawDescGZIP(), []int{12}
}

func (x *SoldadosAnswer) GetCantidadSoldados() int32 {
	if x != nil {
		return x.CantidadSoldados
	}
	return 0
}

func (x *SoldadosAnswer) GetPlanetaEmisor() string {
	if x != nil {
		return x.PlanetaEmisor
	}
	return ""
}

func (x *SoldadosAnswer) GetRelojVectorial() []int32 {
	if x != nil {
		return x.RelojVectorial
	}
	return nil
}

var File_Proto_message_proto protoreflect.FileDescriptor

var file_Proto_message_proto_rawDesc = []byte{
	0x0a, 0x13, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x55, 0x0a, 0x0b, 0x43,
	0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63,
	0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65,
	0x6c, 0x6f, 0x6a, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69,
	0x61, 0x6c, 0x22, 0x1d, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x63,
	0x69, 0x62, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x63, 0x69, 0x62,
	0x6f, 0x22, 0x1e, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x76, 0x69, 0x73, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x76, 0x69, 0x73,
	0x6f, 0x22, 0x4f, 0x0a, 0x11, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65,
	0x6c, 0x6f, 0x6a, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69,
	0x61, 0x6c, 0x22, 0x30, 0x0a, 0x10, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x50,
	0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6f, 0x6c, 0x69, 0x63, 0x69,
	0x74, 0x75, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x6c, 0x69, 0x63,
	0x69, 0x74, 0x75, 0x64, 0x22, 0x68, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x44,
	0x65, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x64, 0x6f, 0x12, 0x2c, 0x0a, 0x11, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x63, 0x69, 0x6f, 0x6e, 0x41, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x64, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x64, 0x69, 0x72, 0x65, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x41, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x64, 0x61, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x75, 0x65, 0x72, 0x74, 0x6f,
	0x41, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x64, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x70, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x41, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x64, 0x6f, 0x22, 0x49,
	0x0a, 0x05, 0x43, 0x72, 0x65, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62,
	0x61, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x22, 0x70, 0x0a, 0x0c, 0x43, 0x61, 0x6d,
	0x62, 0x69, 0x6f, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x4f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6e, 0x6f, 0x6d, 0x62, 0x72,
	0x65, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x4e, 0x75, 0x65, 0x76, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x4e, 0x75, 0x65, 0x76, 0x6f, 0x22, 0x58, 0x0a, 0x0a, 0x41,
	0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x75, 0x65, 0x76, 0x6f, 0x56, 0x61,
	0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x75, 0x65, 0x76, 0x6f,
	0x56, 0x61, 0x6c, 0x6f, 0x72, 0x22, 0x34, 0x0a, 0x06, 0x42, 0x6f, 0x72, 0x72, 0x61, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x6b, 0x0a, 0x0f, 0x43,
	0x6f, 0x64, 0x69, 0x67, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61,
	0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x22, 0x3d, 0x0a, 0x0f, 0x53, 0x6f, 0x6c, 0x64,
	0x61, 0x64, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x0e, 0x53, 0x6f, 0x6c, 0x64,
	0x61, 0x64, 0x6f, 0x73, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x61,
	0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x53, 0x6f, 0x6c, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x63, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x53, 0x6f,
	0x6c, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74,
	0x61, 0x45, 0x6d, 0x69, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70,
	0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x45, 0x6d, 0x69, 0x73, 0x6f, 0x72, 0x12, 0x26, 0x0a, 0x0e,
	0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x69, 0x61, 0x6c, 0x32, 0x8a, 0x04, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x6c,
	0x61, 0x6e, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x6f, 0x6c, 0x69,
	0x63, 0x69, 0x74, 0x75, 0x64, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x1a, 0x16, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x44, 0x65, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x64, 0x6f, 0x12, 0x31, 0x0a, 0x0b, 0x41, 0x67, 0x72, 0x65, 0x67, 0x61, 0x72, 0x42,
	0x61, 0x73, 0x65, 0x12, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x72,
	0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x3a, 0x0a, 0x0d, 0x52, 0x65, 0x6e, 0x6f, 0x6d,
	0x62, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x12, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x43, 0x61, 0x6d, 0x62, 0x69, 0x6f, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x1a, 0x15, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65,
	0x73, 0x74, 0x61, 0x12, 0x3a, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x72, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x63,
	0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x43, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12,
	0x31, 0x0a, 0x0a, 0x42, 0x6f, 0x72, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x12, 0x0c, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x61, 0x72, 0x1a, 0x15, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x43, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x12, 0x3a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6c, 0x64, 0x61, 0x64, 0x6f,
	0x73, 0x12, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x6f, 0x6c, 0x64, 0x61, 0x64, 0x6f,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x6f, 0x6c, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x3c,
	0x0a, 0x0d, 0x53, 0x6f, 0x6c, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12,
	0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x6f, 0x6c, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x6f,
	0x6c, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x0c,
	0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x2c, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x63, 0x69, 0x61, 0x12, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x1a, 0x09, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x63,
	0x6b, 0x42, 0x0f, 0x5a, 0x0d, 0x53, 0x44, 0x2f, 0x4c, 0x41, 0x42, 0x33, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Proto_message_proto_rawDescOnce sync.Once
	file_Proto_message_proto_rawDescData = file_Proto_message_proto_rawDesc
)

func file_Proto_message_proto_rawDescGZIP() []byte {
	file_Proto_message_proto_rawDescOnce.Do(func() {
		file_Proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_Proto_message_proto_rawDescData)
	})
	return file_Proto_message_proto_rawDescData
}

var file_Proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_Proto_message_proto_goTypes = []interface{}{
	(*Consistency)(nil),       // 0: grpc.Consistency
	(*Ack)(nil),               // 1: grpc.Ack
	(*Signal)(nil),            // 2: grpc.Signal
	(*MergeAnswerString)(nil), // 3: grpc.MergeAnswerString
	(*SolicitudPlaneta)(nil),  // 4: grpc.SolicitudPlaneta
	(*PlanetaDesignado)(nil),  // 5: grpc.PlanetaDesignado
	(*Crear)(nil),             // 6: grpc.Crear
	(*CambioNombre)(nil),      // 7: grpc.CambioNombre
	(*Actualizar)(nil),        // 8: grpc.Actualizar
	(*Borrar)(nil),            // 9: grpc.Borrar
	(*CodigoRespuesta)(nil),   // 10: grpc.CodigoRespuesta
	(*SoldadosRequest)(nil),   // 11: grpc.SoldadosRequest
	(*SoldadosAnswer)(nil),    // 12: grpc.SoldadosAnswer
}
var file_Proto_message_proto_depIdxs = []int32{
	4,  // 0: grpc.MessageService.GetPlanet:input_type -> grpc.SolicitudPlaneta
	6,  // 1: grpc.MessageService.AgregarBase:input_type -> grpc.Crear
	7,  // 2: grpc.MessageService.RenombrarBase:input_type -> grpc.CambioNombre
	8,  // 3: grpc.MessageService.ActualizarValor:input_type -> grpc.Actualizar
	9,  // 4: grpc.MessageService.BorrarBase:input_type -> grpc.Borrar
	11, // 5: grpc.MessageService.GetSoldados:input_type -> grpc.SoldadosRequest
	11, // 6: grpc.MessageService.SoldadosQuery:input_type -> grpc.SoldadosRequest
	2,  // 7: grpc.MessageService.MergeRequest:input_type -> grpc.Signal
	0,  // 8: grpc.MessageService.Consistencia:input_type -> grpc.Consistency
	5,  // 9: grpc.MessageService.GetPlanet:output_type -> grpc.PlanetaDesignado
	10, // 10: grpc.MessageService.AgregarBase:output_type -> grpc.CodigoRespuesta
	10, // 11: grpc.MessageService.RenombrarBase:output_type -> grpc.CodigoRespuesta
	10, // 12: grpc.MessageService.ActualizarValor:output_type -> grpc.CodigoRespuesta
	10, // 13: grpc.MessageService.BorrarBase:output_type -> grpc.CodigoRespuesta
	12, // 14: grpc.MessageService.GetSoldados:output_type -> grpc.SoldadosAnswer
	12, // 15: grpc.MessageService.SoldadosQuery:output_type -> grpc.SoldadosAnswer
	3,  // 16: grpc.MessageService.MergeRequest:output_type -> grpc.MergeAnswerString
	1,  // 17: grpc.MessageService.Consistencia:output_type -> grpc.Ack
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_Proto_message_proto_init() }
func file_Proto_message_proto_init() {
	if File_Proto_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Proto_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Consistency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeAnswerString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudPlaneta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlanetaDesignado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Crear); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CambioNombre); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Actualizar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Borrar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodigoRespuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoldadosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_message_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoldadosAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Proto_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Proto_message_proto_goTypes,
		DependencyIndexes: file_Proto_message_proto_depIdxs,
		MessageInfos:      file_Proto_message_proto_msgTypes,
	}.Build()
	File_Proto_message_proto = out.File
	file_Proto_message_proto_rawDesc = nil
	file_Proto_message_proto_goTypes = nil
	file_Proto_message_proto_depIdxs = nil
}
