combine:
	cd Combine; go run main.go
rebeldes:
	cd Rebeldes; go run main.go
namenode:
	cd NameNode; go run namenode.go
grunt:
	cd Grunt; go run datanode.go
synth:
	cd Synth; go run datanode.go
cremator:
	cd Cremator; go run datanode.go